### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [lisitsyn/tapkee#14]
Some parameters (like "${CMAKE_CURRENT_SOURCE_DIR}/lib" and "${CMAKE_BINARY_DIR}") are passed to CMake commands in [your build script](https://github.com/lisitsyn/tapkee/blob/217bb9f7783eceff3ed1a48f7ec2008bd9168dd5/CMakeLists.txt#L11 "build commands") without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like spaces.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by elfring** [comment]
Thanks for [your improvement of the affected build script](https://github.com/lisitsyn/tapkee/commit/399ec1c062fcd214876f6fcbf19b0e64cbacbc44 "Improvements for a CMake script").

How do you think about to integrate another small update like the following?
```diff
-			include_directories(${GTEST_SOURCE_DIR})
-			include_directories(${GTEST_INCLUDE_DIR}/include)
+ 			include_directories("${GTEST_SOURCE_DIR}" "${GTEST_INCLUDE_DIR}/include")
```

**Comment by lisitsyn** [comment]
@elfring thanks! Updated that in 215f7e0fdcecd59ad8107c77c97dc2236fbefc12
