### ISSUE TITLE
ezoptionparser error

### ISSUE THREAD

**Issue by skn123** [lisitsyn/tapkee#20]
```
        case S1: CHECKRANGE(S1,char); break;
        case U1: CHECKRANGE(U1,unsigned char); break;
        case S2: CHECKRANGE(S2,short); break;
        case U2: CHECKRANGE(U2,unsigned short); break;
        case S4: CHECKRANGE(S4,int); break;
        case U4: CHECKRANGE(U4,unsigned int); break;
```

Error   34  error C2589: '(' : illegal token on right side of '::'  ...

**Comment by iglesias** [comment]
> ```
>         case S1: CHECKRANGE(S1,char); break;
>         case U1: CHECKRANGE(U1,unsigned char); break;
>         case S2: CHECKRANGE(S2,short); break;
>         case U2: CHECKRANGE(U2,unsigned short); break;
>         case S4: CHECKRANGE(S4,int); break;
>         case U4: CHECKRANGE(U4,unsigned int); break;
> ```
> 
> Error 34 error C2589: '(' : illegal token on right side of '::' ...

There are no '::' in the snippet and I did not reproduce any build error.
