### ISSUE TITLE
search condition in the vp tree in tapkee

### ISSUE THREAD

**Issue by coderlevi** [lisitsyn/tapkee#33]
in the vptree.hpp file, the search() function contains this code block:

                if (distance < node->threshold)
                {
                        if ((distance - tau) <= node->threshold)
                                search(node->left, target, k, heap);

                        if ((distance + tau) >= node->threshold)
                                search(node->right, target, k, heap);
                }
                else
                {
                        if ((distance + tau) >= node->threshold)
                                search(node->right, target, k, heap);

                        if ((distance - tau) <= node->threshold)
                                search(node->left, target, k, heap);
                }

Are second and fourth if necessary here ?

The first if says "distance < node->threshold", then the second if "(distance - tau) <= node->threshold" should be satisfied automatically, right ?  Same is for the fourth if.

So I think we may simplify this code block to:

                if (distance < node->threshold)
                {
                        search(node->left, target, k, heap);

                        if ((distance + tau) >= node->threshold)
                                search(node->right, target, k, heap);
                }
                else
                {
                        search(node->right, target, k, heap);

                        if ((distance - tau) <= node->threshold)
                                search(node->left, target, k, heap);
                }

Correct me if I am wrong. Thanks

**Comment by iglesias** [comment]
The simplification makes sense to me.

**Comment by lisitsyn** [comment]
Same for me, looks valid. 

Although once we do such changes we should stop treating it 'external' - it was so as this code is extracted from Laurens' software.
