### ISSUE TITLE
MultidimensionalScaling with input type of std::vector<DenseVector>

### ISSUE THREAD

**Issue by tangbohu** [lisitsyn/tapkee#38]
Instead using vector < IndexType >  indices(N) as the input, I use std::vector < DenseVector >  for the MultidimensionalScaling method. The code crash all the time. Can you give me a example to
run these type of data? Thanks.

**Comment by lisitsyn** [comment]
Thanks for reporting an issue. I'll get back to you in a bit with more information.

**Comment by lisitsyn** [comment]
@tangbohu I have modified `minimal` example so it uses an std::vector of dense vectors. Here is the source:

```cpp
#include <tapkee/tapkee.hpp>

using namespace std;
using namespace tapkee;

struct MyDistanceCallback
{
	ScalarType distance(DenseVector l, DenseVector r)
	{
		return (l-r).sum();
	}
};

int main(int argc, const char** argv)
{
	const int N = 100;
	vector<DenseVector> vectors(N);
	for (int i=0; i<N; i++) vectors[i] = DenseVector::Random(3);

	MyDistanceCallback distance;

	TapkeeOutput output = initialize()
	  .withParameters((method=MultidimensionalScaling,
	                   target_dimension=1))
	  .withDistance(distance)
	  .embedUsing(vectors);

	cout << output.embedding.transpose() << endl;

	return 0;
}```

It worked and the result I've got was:
```1.27401    0.627554    0.237896   -0.626915     1.21031    0.631212     1.31282    -1.36406    0.118186    -0.49391   -0.821636    0.824746    -1.71187   -0.141548    -1.20676   -0.129748   0.0970751     1.06748     1.02373    -0.68655   -0.802629   -0.550996    0.439024     1.13111   -0.392986    0.137288    -1.67076     1.38893    -1.41972    -2.17858     1.26724    -0.85243  0.00249002    0.207075     1.80979    0.234079   -0.928274    -1.33892   -0.205005     0.93253     2.31115    0.746329    0.330899    -0.66487    0.613315    0.978309   -0.997434   -0.271106  -0.0194757    0.437228  -0.0540056    0.751755    0.249108 -0.00638573     1.80643    0.107923   0.0703307    0.768266     1.66939    0.301168    -0.17323    -0.54883   -0.628972   -0.627849    -1.29929    -1.04439    -0.85771    -2.23923   -0.307716    0.984513   -0.738335      -1.581    -1.44964    0.188086     0.56443   -0.629035   -0.915835  -0.0980166   -0.262176    0.495477   -0.529216    0.281654   -0.518111     1.81266   -0.591422   -0.513252   -0.452897     1.03832    -0.16655     1.68145    -1.53081     0.55747   -0.918074     2.07343     0.21008    0.339658   -0.164183    0.242634     1.93901    -1.20268```

Could you please provide your example so we can debug it?

**Comment by tangbohu** [comment]
#include <tapkee/tapkee.hpp>
#include<iostream>
#include<algorithm>
using namespace std;
using namespace tapkee;


struct MyDistanceCallback
{
	ScalarType distance(DenseVector l, DenseVector r)
	{
		double dist2 = pow(l[0] - r[0], 2) + pow(l[1] - r[1], 2) + pow(l[2] - r[2], 2);
		dist2 = sqrt(dist2);
		return std::abs(0.5 - dist2);
	}
};

int main(int argc, const char** argv)
{
	const int N = 30;
	vector<DenseVector> vectors;

	DenseVector temp1(3);
	temp1 << 0, 0, 0;
	vectors.push_back(temp1);

	DenseVector temp2(3);
	temp2 << 0.5, 0, 0;
	vectors.push_back(temp2);

	DenseVector temp3(3);
	temp3 << 0.4, 0, 0;
	vectors.push_back(temp3);

	DenseVector temp4(3);
	temp4 << 0.3, 0, 0;
	vectors.push_back(temp4);


	DenseVector temp5(3);
	temp5 << 0.3, 0,1, 0;
	vectors.push_back(temp5);

	for (int i = 0; i<N; i++) vectors.push_back( DenseVector::Random(3));
	std::cout << "vector's size is " << vectors.size() << endl;

	MyDistanceCallback distance;

	TapkeeOutput output = initialize()
		.withParameters((method = MultidimensionalScaling,
		target_dimension = 1))
		.withDistance(distance)
		.embedUsing(vectors);

	std::cout << "output's size is " << output.embedding.cols()<<"  *  "<<output.embedding.rows() << endl;
	cout << output.embedding.transpose() << endl;

	return 0;
}


The above is my code, and the outputs are as follows:
vector's size is 35
landmark ratio is 0.000000
output's size is 1  *  35
 0.0208803   0.263443   0.208528   0.158147   0.395647  -0.559559   0.414352   0.428025  0.0937686   0.183734   -1.03064  -0.507604  -0.678742  -0.593741   0.221299  -0.147566  -0.538635   0.646216
 0.31146    1.05815  -0.474362   0.227713    1.24647 -0.0549218  0.0250521  -0.438772  -0.853972   -0.37258   0.663802   -0.18068   0.134634 -0.0917809   0.188079  -0.169734  -0.196106

As the original distance between the first two input values is 0.5, thus after embedding, their distance should be zero or a very small integer, however, the output is so much larger. Is there some thing wrong with my code? Waiting for your reply.
