### ISSUE TITLE
Issue in PCA's projection function

### ISSUE THREAD

**Issue by Aneoshun** [lisitsyn/tapkee#45]
Hi all, 

Thanks for this library, I think it can be useful for my own research. 

I am trying to use the projection function of the PCA. However, the result of the project is always a vector with the length of the high-dimensional space. Also, a dimension analysis of the matrix/vectors of the projection function, shows that there is something weird. Is this a bug or am I missing something?

I suspect that there is a .transpose() missing in the definition of the projection function  [Here](https://github.com/lisitsyn/tapkee/blob/14b57ff9b205baad074a73a7f618e65909ead12a/include/tapkee/methods.hpp#L457)

I tested this on my side, and I managed to retrieve the embedding after projecting the training dataset with my modified projection function. 

Thanks

**Comment by lisitsyn** [comment]
Hey @Aneoshun,

thanks for reporting. Let me check and get back to you.

**Comment by lisitsyn** [comment]
I tried adding transpose in PR #46 and it fixed the problem indeed. Although the tests are failing on Travis, it might be due to Eigen versions.
