### ISSUE TITLE
Running tapkee 

### ISSUE THREAD

**Issue by Horytsvit** [lisitsyn/tapkee#54]
Hi there, 

Thanks for a wonderful program! For some reason, I could not run 'tapkee' on my comp (OS: Windows 7). When I open the downloaded file, it, first, asks me whether I want to run the program. As I hit 'run', for a millisecond, a window appears and disappears instantly. I tried to run in the Windows console, but it says that ''tapkee' is not recognized as an internal or external command, operable program or batch file'. I wonder what I am doing wrong.

**Comment by iglesias** [comment]
Hey! Could you provide some additional information?
For example, what downloaded file did you open, did you successfully compile the application?

**Comment by Horytsvit** [comment]
Hi Fernando, thanks for your reply! Actually, the guy from the YouTube channel 'Machine Learning at Home', from where I had learnt about 'tapkee' helped to fix the problem. There was a problem with coping the downloaded file into chosen directory. Now it is solved. Thanks for getting back!
